name: Metrics

on:
  # æ¯å¤©åŒ—äº¬æ—¶é—´ 00:00 æ›´æ–°
  schedule: [{ cron: "0 16 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # ğŸ“— Classic template
          template: classic
          base: header, metadata
          # ğŸ“… Half year calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_topics: yes 
          plugin_topics_sort: stars 
          plugin_topics_mode: starred 
          plugin_topics_limit: 15 
          plugin_languages: yes 
          plugin_languages_ignored: >- 
            html, css 
          plugin_languages_details: bytes-size, percentage

          # ğŸ’¡ Coding habits and activity
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_from: 400
          plugin_habits_days: 30
          plugin_habits_charts_type: graph
          plugin_habits_trim: yes
